### ISSUE TITLE
Error:Platform Windows isn't supported for execution.

### ISSUE THREAD

**Issue by richard14110** [phr00t/FocusEngine#110]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Latest official release.

**Version**: Version number and/or git branch
3.8.5

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows 10

**Describe the bug**
Both building and starting a project give me the same error.

**To Reproduce**
I'm uncertain if the issue can be reproduced on someone else's computer. I have the Visual Studio 2022 with the .NET desktop development, Desktop development with C++, Windows 10 SDK (latest), VC++ 2022 latest v143 tools workloads and the .NET Framework 4.8 Developer Pack and Targeting Pack installed.

**Expected behavior**
Before I expected the compilation to begin.

**Screenshots**
![Error Platform Windows isn't supported for execution](https://user-images.githubusercontent.com/6833439/172276801-0f89cd7d-c876-474e-ae74-21bfb56f1d8d.png)

**Log and callstacks**
N/A

**Additional context**
Fortunately, I am able to load the third-person platformer sample and the other editor functions work.

**Comment by phr00t** [comment]
Building and running from the editor doesn't work correctly. Visual Studio does that far better, so that's where you should go. Open the project in Visual Studio and run there and it should work fine. I do use editor building to display shader errors, though. Frankly, I should just remove that run option from the editor.

**Comment by phr00t** [comment]
Also, I should remove that official release or update it. 3.8.5 is horribly out of date.

**Comment by richard14110** [comment]
A long time ago, starting and building the project did work for me from within the editor but I don't know what settings I need to get it to be the same as before. Instead of removing the run option, can you make it a simulate feature that skips compiling the files? That saves time for people with a low end processor (including myself). The last time I remember, it took many minutes to build the sample on my computer so I would prefer if it only takes seconds to start testing a scene. It might be the best of both worlds if someone can quickly play a scene inside the editor and compile with Visual Studio.

**Comment by phr00t** [comment]
Looking at my latest version, 4.5.3, I did actually remove the "Run" thing a long time ago to avoid this confusion. You can't really run the scene without running (and checking to see if it needs compilation) the code alongside it. In the latest version, I do skip asset recompilation if none of the assets changed, which saves time (but if you changed the scene, assets do need to be recompiled). Anyway, the bottom line is, I don't want to maintain a feature in GameStudio that Visual Studio already maintains and does better. GameStudio might do something a little faster, probably because it isn't doing everything it really needs to.
